/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.nicoarianto

import org.springframework.boot.autoconfigure.EnableAutoConfiguration
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
@EnableAutoConfiguration
class MainApplication

fun main(args: Array<String>) {
    runApplication<MainApplication>(*args)
}
